// The original game's energy icons, pixel for pixel. Used while settings.modelStyle is
// 'classic'; see enhancedIcons below for the redrawn set.
const classicIcons = {
	tree: 'iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABUSURBVDhPY/z//z8DIRB9KwGuaKnaAkYoEydggtJUBaOGUh/gjH1cMU5MShiNKOoD2sc+qXkcl/oh5P2om/EI/yMBUr2PDIZo7OMCpKaKoeJ9BgYABCoqqw/G+rYAAAAASUVORK5CYII=',
	boulder:
		'iVBORw0KGgoAAAANSUhEUgAAABgAAAAVCAMAAABrN94UAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJUExURQAAAFq6vQAAAJsZRKMAAAADdFJOU///ANfKDUEAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAqSURBVChTY2DCAQaDBCMSgIiQIQHlYQBKJCBGQzkUSEBEIQAiMoASjIwAVeMDB6v17KcAAAAASUVORK5CYII=',
	synthoid:
		'iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABKSURBVDhPY/z//z8DNjBz9l/sEkggPZWZEcpEAUxQmqqAJobi9D4lYAh5f8asP1T3/zDwPq6EjQxwZZCh4/0RbugIL/pGtKEMDABrnht3eidv4gAAAABJRU5ErkJggg==',
	golden: 'iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABKSURBVDhPY/z//z8DNvD9Jzt2CSTAyf6TEcpEAUxQmqqAJobi9D4lYAh5/9sPNqr7fxh4H1fCRga4MsjQ8f4IN3SEF30j2lAGBgBe8hsDa4xyzAAAAABJRU5ErkJggg==',
};

export default classicIcons;

/*
 The redrawn energy icons, used while settings.modelStyle is 'enhanced'.

 SVG rather than a base64 PNG, and kept as readable source rather than a blob, for three reasons:
 they stay crisp at any device pixel ratio (the originals are 21px bitmaps and are visibly soft on
 a phone), they are a couple of hundred bytes each, and — the one that actually matters day to day
 — a coordinate or a colour can be edited here by hand instead of regenerated by a tool.

 Each is drawn in the flat-facet language of the models they stand for and in those models' own
 palette (see C in utils/gen-models.mjs), so the icon and the thing it refers to agree: conifer
 tiers over a bark trunk, a chamfered stone block lit from above, and the legless synthoid with its
 visor. `golden` is the synthoid in gold — it is the 15-energy denomination, not a different object,
 so it must read as the same shape.
*/
export const enhancedIcons = {
	tree: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="22" height="22"><rect x="10.6" y="17.5" width="2.8" height="5.5" fill="#4a3524"/><rect x="12" y="17.5" width="1.4" height="5.5" fill="#3a291c"/><polygon points="12,11.0 19.0,19.5 12,19.5" fill="#1d5a2a"/><polygon points="12,11.0 12,19.5 5.0,19.5" fill="#2c7d3a"/><polygon points="12,6.0 17.2,14.0 12,14.0" fill="#1d5a2a"/><polygon points="12,6.0 12,14.0 6.8,14.0" fill="#2c7d3a"/><polygon points="12,1.4 15.6,8.6 12,8.6" fill="#1d5a2a"/><polygon points="12,1.4 12,8.6 8.4,8.6" fill="#2c7d3a"/></svg>',
	boulder: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="22" height="22"><polygon points="12,4.6 19.4,9.0 12,13.4 4.6,9.0" fill="#878b90"/><polygon points="4.6,9.0 12,13.4 12,20.4 4.6,16.0" fill="#6f7378"/><polygon points="19.4,9.0 12,13.4 12,20.4 19.4,16.0" fill="#54585c"/></svg>',
	synthoid: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="22" height="22"><rect x="6.0" y="11.2" width="1.9" height="4.6" fill="#1f4c5e"/><rect x="16.1" y="11.2" width="1.9" height="4.6" fill="#1f4c5e"/><polygon points="9.3,10.2 14.7,10.2 17.0,22.4 7.0,22.4" fill="#2f6f88"/><polygon points="12,10.2 14.7,10.2 17.0,22.4 12,22.4" fill="#27607a"/><polygon points="8.7,3.2 15.3,3.2 16.4,6.4 15.3,10.2 8.7,10.2 7.6,6.4" fill="#3f8ea8"/><polygon points="12,3.2 15.3,3.2 16.4,6.4 15.3,10.2 12,10.2" fill="#2f6f88"/><rect x="8.9" y="5.6" width="6.2" height="2.4" fill="#36d8d0"/></svg>',
	golden: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="22" height="22"><rect x="6.0" y="11.2" width="1.9" height="4.6" fill="#7a5f12"/><rect x="16.1" y="11.2" width="1.9" height="4.6" fill="#7a5f12"/><polygon points="9.3,10.2 14.7,10.2 17.0,22.4 7.0,22.4" fill="#c8a22a"/><polygon points="12,10.2 14.7,10.2 17.0,22.4 12,22.4" fill="#a9871f"/><polygon points="8.7,3.2 15.3,3.2 16.4,6.4 15.3,10.2 8.7,10.2 7.6,6.4" fill="#e8c451"/><polygon points="12,3.2 15.3,3.2 16.4,6.4 15.3,10.2 12,10.2" fill="#c8a22a"/><rect x="8.9" y="5.6" width="6.2" height="2.4" fill="#fff0a8"/></svg>',
};

export type IconName = keyof typeof enhancedIcons;

/*
 An <img> source for one icon. The enhanced set is inlined as a data URI rather than served from
 public/: four files' worth of network for a few hundred bytes each is a poor trade, and it keeps
 the HUD working before anything has loaded.
*/
export function iconSrc(name: IconName, enhanced: boolean): string {
	if (enhanced) return 'data:image/svg+xml,' + encodeURIComponent(enhancedIcons[name]);
	return 'data:image/png;base64,' + classicIcons[name];
}
