/*
 Generate the object models in src/world/objects/models/*.ts.

 WHY A GENERATOR. The model format is a hand-maintained list of vertices and 1-based triangle
 indices with a flat colour per face (see models/index.ts). That is fine for the 12-triangle
 boulder the game shipped with and hopeless for anything detailed — the old pipeline was "export
 an .obj, run utils/obj-shrink.js, transcribe by hand and re-assign every face colour", which is
 both laborious and unreviewable. Built from primitives instead, a model is a few lines that say
 what it IS, a change is an edit and a re-run, and the numbers are always consistent.

 WHAT MUST NOT CHANGE. These are the DRAWN shapes only. The shapes that answer raycasts are the
 originals, kept as occluders (models/index.ts's getOccluder), so silhouette changes here cannot
 move a line of sight. Two things still matter visually:
   - stacking heights: a boulder's top face must sit at exactly BOULDER_RISE (0.5) and a
     pedestal's at PEDESTAL_RISE (1.0), or things placed on them float or sink;
   - the overall envelope should stay close to the occluder, so the crosshair and the drawn
     model agree about where a thing is.

   node utils/gen-models.mjs
*/
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const OUT = resolve(import.meta.dirname, '..', 'src', 'world', 'objects', 'models');

// ---- primitives ---------------------------------------------------------------------------
// Every builder pushes into a shared {v, f} accumulator. Vertices are deduplicated on exact
// coordinates, which keeps the files small without an obj-shrink pass.
function Model() {
	const v = [];
	const f = [];
	const index = new Map();
	const R = n => Math.round(n * 4096) / 4096;      // tidy binary fractions, like the originals
	const vert = (x, y, z) => {
		const key = `${R(x)},${R(y)},${R(z)}`;
		if (index.has(key)) return index.get(key);
		v.push([R(x), R(y), R(z)]);
		index.set(key, v.length);
		return v.length;                              // 1-based, OBJ convention
	};
	const tri = (a, b, c, color) => f.push({ v: [a, b, c], color });
	const quad = (a, b, c, d, color) => { tri(a, b, c, color); tri(a, c, d, color); };
	return { v, f, vert, tri, quad,
		// A ring of n points at radius r, height y, optionally spun by `phase` turns.
		ring(n, r, y, phase = 0, sx = 1, sz = 1) {
			return Array.from({ length: n }, (_, i) => {
				const a = ((i + phase) / n) * Math.PI * 2;
				return vert(Math.sin(a) * r * sx, y, Math.cos(a) * r * sz);
			});
		},
		/*
		 An 8-point ring shaped as a CHAMFERED SQUARE — points at (±hw, ±c) and (±c, ±hw) — rather
		 than a regular octagon. It matters for the pedestal: a regular octagon inscribed in the
		 same bounding box leaves the four corners empty, and since the pedestal's occluder is a
		 full square those empty corners are exactly where you can see through the drawn model and
		 still be refused by the crosshair.
		*/
		squareRing(hw, c, y) {
			return [
				vert(c, y, hw), vert(hw, y, c), vert(hw, y, -c), vert(c, y, -hw),
				vert(-c, y, -hw), vert(-hw, y, -c), vert(-hw, y, c), vert(-c, y, hw),
			];
		},
		// Side wall between two rings of equal length.
		skirt(lower, upper, color, colorAlt) {
			const n = lower.length;
			for (let i = 0; i < n; i++) {
				const j = (i + 1) % n;
				quad(lower[i], lower[j], upper[j], upper[i], colorAlt && i % 2 ? colorAlt : color);
			}
		},
		// Flat cap over a ring. `up` false emits the reversed winding for a floor.
		cap(r, color, up = true) {
			const c = r.length;
			for (let i = 1; i < c - 1; i++) up ? tri(r[0], r[i], r[i + 1], color) : tri(r[0], r[i + 1], r[i], color);
		},
		// Axis-aligned box, given as centre + half extents.
		box(cx, cy, cz, hx, hy, hz, color, top = color) {
			const x0 = cx - hx, x1 = cx + hx, y0 = cy - hy, y1 = cy + hy, z0 = cz - hz, z1 = cz + hz;
			const a = vert(x0, y0, z1), b = vert(x1, y0, z1), c = vert(x1, y0, z0), d = vert(x0, y0, z0);
			const e = vert(x0, y1, z1), g = vert(x1, y1, z1), h = vert(x1, y1, z0), i = vert(x0, y1, z0);
			quad(a, b, g, e, color); quad(b, c, h, g, color);
			quad(c, d, i, h, color); quad(d, a, e, i, color);
			quad(e, g, h, i, top);   quad(d, c, b, a, color);
		},
	};
}

function emit(name, m) {
	const vs = m.v.map(p => `\t\t[${p.join(', ')}],`).join('\n');
	const fs = m.f.map(t => `\t\t{ v: [${t.v.join(', ')}], color: ${t.color} },`).join('\n');
	const body = `// GENERATED by utils/gen-models.mjs — edit that, not this file.\n` +
		`// ${m.f.length} triangles, ${m.v.length} vertices.\n` +
		`export const ${name} = {\n\tv: [\n${vs}\n\t],\n\tf: [\n${fs}\n\t],\n};\n`;
	writeFileSync(resolve(OUT, `${name}.ts`), body);
	console.log(`${name.padEnd(9)} ${String(m.f.length).padStart(4)} tris  ${String(m.v.length).padStart(4)} verts`);
}

// ---- palette ------------------------------------------------------------------------------
// Theme-tinted faces (-1 / -2) are gone. They existed so the pedestal and a couple of trim faces
// picked up the landscape palette, but with eight themed grounds a synthoid that changes colour
// with the terrain reads as part of the scenery — and the one thing a player must never lose
// track of is which shapes are ALIVE. The cast keeps a fixed identity instead.
const C = {
	bark: 0x4a3524, barkLit: 0x5d4430,
	needle: 0x1d5a2a, needleLit: 0x2c7d3a, needleDark: 0x12401d,
	stone: 0x6f7378, stoneLit: 0x878b90, stoneDark: 0x54585c,
	plinth: 0x2b2f36, plinthLit: 0x3a3f47, gold: 0xc8a22a, goldLit: 0xe8c451,
	shell: 0xb03030, shellLit: 0xd04a44, shellDark: 0x7a1e1e,
	// Cool for the body you inhabit, warm for everything that wants you gone. The player can be
	// looking at a synthoid and a sentry across a valley at the same moment and has to tell them
	// apart instantly; hue does that at a distance where silhouette does not.
	hull: 0x2f6f88, hullLit: 0x3f8ea8, hullDark: 0x1f4c5e,
	dark: 0x14161a, darkLit: 0x22262c,
	visor: 0xffd23c, visorDim: 0xc79a10,
	steel: 0x7c8894, steelLit: 0x9aa6b2, steelDark: 0x5a6672,
	cyan: 0x36d8d0, ember: 0xff7a1a, emberDim: 0xc25200,
};

// ---- tree ---------------------------------------------------------------------------------
// Stays a pine: the cone is functional, not decorative — a player reads tree-shaped as "one
// energy, and it hides nothing". Three stacked tiers instead of one smooth cone give it some
// craft without touching the silhouette that matters.
function tree() {
	const m = Model(), H = 1.8125;
	const foot = m.ring(8, 0.16, 0), top = m.ring(8, 0.10, 0.34);
	m.skirt(foot, top, C.bark, C.barkLit);
	m.cap(foot, C.bark, false);
	const tiers = [[0.30, 0.4063, 0.72], [0.62, 0.3200, 1.16], [1.02, 0.2200, 1.56]];
	for (const [base, r, tip] of tiers) {
		const low = m.ring(8, r, base), mid = m.ring(8, r * 0.62, base + (tip - base) * 0.45);
		m.skirt(low, mid, C.needle, C.needleLit);
		m.cap(low, C.needleDark, false);
		const apex = m.vert(0, tip, 0);
		for (let i = 0; i < 8; i++) m.tri(mid[i], mid[(i + 1) % 8], apex, i % 2 ? C.needle : C.needleLit);
	}
	const crown = m.ring(8, 0.16, 1.42), apex = m.vert(0, H, 0);
	for (let i = 0; i < 8; i++) m.tri(crown[i], crown[(i + 1) % 8], apex, i % 2 ? C.needleLit : C.needle);
	return m;
}

// ---- boulder ------------------------------------------------------------------------------
// A cut grey block, as asked. TOP FACE AT EXACTLY y=0.5: engine/scene.ts's BOULDER_RISE says a
// boulder raises the surface by half a unit, and game/botGeometry.ts repeats the number, so a
// block of any other height would put every stacked object visibly off its own footing.
function boulder() {
	const m = Model(), TOP = 0.5;
	// Square rings, not octagonal: "grey block" was the brief, and a chamfered cube reads as cut
	// stone where a dome reads as a pebble. The chamfer is what keeps it from being a plain box.
	const foot = m.ring(4, 0.5000, 0, 0.5);
	const lower = m.ring(4, 0.5800, 0.09, 0.5);
	const upper = m.ring(4, 0.5500, TOP - 0.08, 0.5);
	const top = m.ring(4, 0.4600, TOP, 0.5);
	m.skirt(foot, lower, C.stoneDark, C.stone);
	m.skirt(lower, upper, C.stone, C.stoneLit);
	m.skirt(upper, top, C.stoneLit, C.stone);
	m.cap(top, C.stoneLit);
	m.cap(foot, C.stoneDark, false);
	return m;
}

// ---- pedestal -----------------------------------------------------------------------------
// TOP AT EXACTLY y=1.0 and flat across the middle: PEDESTAL_RISE, and the surface
// canTargetTopObject queries at yOffset 1 for the Sentinel and for the synthoid that wins.
function pedestal() {
	const m = Model(), TOP = 1.0, HW = 0.5;
	/*
	 THE SIDE PLANES NEVER MOVE OFF ±HW. Not at the plinth, not at the reveal, not at the cap.

	 This is the third attempt and the first two both failed the same way for different reasons: a
	 taper, then a full-width profile with a 0.03 inset over the shaft. Both looked fine and both
	 were wrong in play, because the occluder is the original 1x1 block and ANY inset shows you a
	 tile past the pedestal that the crosshair then refuses, with nothing on screen to explain it.
	 Three hundredths of a unit is enough to be maddening.

	 So the original's construction is copied exactly: a square prism whose four faces sit flat at
	 x=±0.5 and z=±0.5 for the whole height, with only the CORNERS chamfered, and the chamfer
	 widening toward the top. Every bit of decoration here is colour or corner, never width.
	*/
	const rings = [
		[0.00, 0.480, C.plinth,    C.plinthLit],   // base: all but a full square
		[0.10, 0.430, C.plinthLit, C.plinth],
		[0.16, 0.400, C.plinth,    C.plinthLit],   // reveal — a corner step, not an inset
		[0.80, 0.330, C.plinthLit, C.plinth],      // shaft, chamfer opening with height
		[0.86, 0.310, C.gold,      C.goldLit],     // gold course
		[0.93, 0.300, C.goldLit,   C.gold],
		[TOP,  0.290, C.plinthLit, C.plinth],
	];
	const built = rings.map(([y, c]) => m.squareRing(HW, c, y));
	m.cap(built[0], C.dark, false);
	for (let i = 0; i < built.length - 1; i++) m.skirt(built[i], built[i + 1], rings[i][2], rings[i][3]);
	// The corner chamfers leave a triangular gap at every step; the cap closes the top flat at
	// exactly PEDESTAL_RISE, which is the surface canTargetTopObject queries at yOffset 1.
	m.cap(built[built.length - 1], C.plinthLit);
	return m;
}

// ---- synthoid -----------------------------------------------------------------------------
// Humanoid, and deliberately legless: the player never walks, they transfer. A figure that ends
// in a plinth says "this thing is placed, not standing", which is exactly the game's verb.
function synthoid() {
	const m = Model(), H = 0.9375;
	const foot = m.ring(8, 0.2000, 0), skirtTop = m.ring(8, 0.1500, 0.30);
	m.skirt(foot, skirtTop, C.hullDark, C.hull);
	m.cap(foot, C.dark, false);
	const waist = m.ring(8, 0.1400, 0.32), chest = m.ring(8, 0.1850, 0.62);
	m.skirt(skirtTop, waist, C.dark, C.darkLit);
	m.skirt(waist, chest, C.hull, C.hullLit);
	const shoulder = m.ring(8, 0.1700, 0.70);
	m.skirt(chest, shoulder, C.hullDark, C.hull);
	for (const side of [-1, 1]) {
		m.box(side * 0.2150, 0.56, 0, 0.0450, 0.1400, 0.0450, C.hullDark, C.hull);
		m.box(side * 0.2150, 0.40, 0.01, 0.0380, 0.0700, 0.0380, C.dark, C.darkLit);
	}
	const neck = m.ring(8, 0.0800, 0.72), jaw = m.ring(8, 0.1300, 0.78);
	m.skirt(shoulder, neck, C.dark);
	m.skirt(neck, jaw, C.darkLit, C.dark);
	const brow = m.ring(8, 0.1350, H - 0.06), crown = m.ring(8, 0.0900, H);
	m.skirt(jaw, brow, C.hull, C.hullLit);
	m.skirt(brow, crown, C.hullLit, C.hull);
	m.cap(crown, C.hullLit);
	// Visor: the one bright thing on the model, and the reason it stays legible at distance.
	m.box(0, 0.845, 0.1150, 0.0850, 0.0250, 0.0350, C.cyan, C.hullLit);
	return m;
}

// ---- sentry -------------------------------------------------------------------------------
// The Sentinel's lesser cousin: same cowled language, narrower, colder, and mounted rather than
// robed — it is machinery doing the same job with less presence.
function sentry() {
	const m = Model(), H = 0.9375;
	/*
	 Red, like the Sentinel and the Meanie's cap. The sentry is the Sentinel's lesser cousin and
	 the player has to read that instantly from across a valley; grey put it in the same family as
	 the boulders instead. Steel is kept for the column it stands on, which is what separates it
	 from the Sentinel's robed base.
	*/
	const foot = m.ring(8, 0.2100, 0), col0 = m.ring(8, 0.1100, 0.10), col1 = m.ring(8, 0.0950, 0.40);
	m.skirt(foot, col0, C.dark, C.darkLit);
	m.skirt(col0, col1, C.steelDark, C.steel);
	m.cap(foot, C.dark, false);
	// A collar wider than the head it carries: the overhang is what makes a shape look like it is
	// leaning over you, and it is the trick the sentry shares with the Sentinel.
	const collarLow = m.ring(8, 0.2200, 0.44), collarTop = m.ring(8, 0.1900, 0.56);
	m.skirt(col1, collarLow, C.shellDark);
	m.skirt(collarLow, collarTop, C.shell, C.shellLit);
	const bodyTop = m.ring(8, 0.1750, 0.74);
	m.skirt(collarTop, bodyTop, C.shellDark, C.shell);
	const cowlLow = m.ring(8, 0.2000, 0.78), cowlTop = m.ring(8, 0.0750, H);
	m.skirt(bodyTop, cowlLow, C.dark, C.darkLit);
	m.skirt(cowlLow, cowlTop, C.shell, C.shellLit);
	m.cap(cowlTop, C.shellLit);
	/*
	 The visor runs BACK into the cowl rather than sitting on the front of it. At the old depth its
	 rear face stopped level with the surface, so from most angles it read as a bar floating in
	 front of the head instead of something the head is looking through.
	*/
	m.box(0, 0.845, 0.0850, 0.0700, 0.0180, 0.1250, C.ember, C.emberDim);
	return m;
}

// ---- sentinel -----------------------------------------------------------------------------
// The one model that has to carry menace. It gets it from proportion rather than detail: a wide
// robed base tapering to narrow shoulders, a hood that overhangs the face, and a single lit slit
// under it — the silhouette of something looking down at you from its pedestal.
function sentinel() {
	const m = Model(), H = 1.1797;
	const hem = m.ring(8, 0.2460, 0), robe0 = m.ring(8, 0.2350, 0.30), robe1 = m.ring(8, 0.1950, 0.66);
	m.skirt(hem, robe0, C.shellDark, C.shell);
	m.skirt(robe0, robe1, C.shell, C.shellLit);
	m.cap(hem, C.dark, false);
	const chest = m.ring(8, 0.2150, 0.86);
	m.skirt(robe1, chest, C.shell, C.shellLit);
	// Shoulder mantle — a flare that reads as looming from below, which is how it is always seen.
	const mantle = m.ring(8, 0.2600, 0.90), mantleTop = m.ring(8, 0.1750, 0.98);
	m.skirt(chest, mantle, C.dark, C.darkLit);
	m.skirt(mantle, mantleTop, C.gold, C.goldLit);
	const hoodLow = m.ring(8, 0.1700, 1.00), hoodMid = m.ring(8, 0.1650, H - 0.05);
	m.skirt(mantleTop, hoodLow, C.dark);
	m.skirt(hoodLow, hoodMid, C.shellDark, C.shell);
	const crown = m.ring(8, 0.0850, H);
	m.skirt(hoodMid, crown, C.shell, C.shellLit);
	m.cap(crown, C.shellLit);
	// The face: dark recess, one burning slit, overhung by the hood above it.
	m.box(0, 1.075, 0.1500, 0.1000, 0.0450, 0.0300, C.dark, C.dark);
	m.box(0, 1.078, 0.1720, 0.0750, 0.0130, 0.0180, C.visor, C.ember);
	return m;
}

// ---- meanie -------------------------------------------------------------------------------
// A desk lamp with bad intentions, per the brief: trapezoidal base, a jointed arm, and a weapon
// head at the end of it. Reads as a machine that was pointed at you rather than a creature.
function meanie() {
	const m = Model(), H = 0.9219;
	const base0 = m.ring(4, 0.3100, 0, 0.5), base1 = m.ring(4, 0.2050, 0.16, 0.5);
	m.skirt(base0, base1, C.steelDark, C.steel);
	m.cap(base1, C.steel);
	m.cap(base0, C.dark, false);
	// Lower arm, leaning forward; upper arm leaning back — the classic lamp elbow.
	const j0 = m.ring(6, 0.0560, 0.16), j1 = m.ring(6, 0.0480, 0.50);
	m.skirt(j0, j1, C.steel, C.steelLit);
	const elbow = m.ring(6, 0.0700, 0.54);
	m.skirt(j1, elbow, C.cyan);
	const a0 = m.ring(6, 0.0480, 0.56, 0, 1, 1), a1 = m.ring(6, 0.0430, 0.74, 0, 1, 1);
	m.skirt(elbow, a0, C.steelDark);
	m.skirt(a0, a1, C.steel, C.steelLit);
	// Head: a shade tapering to the muzzle, pointed forward (+Z) like every other model.
	const collar = m.ring(8, 0.0850, 0.76), shade = m.ring(8, 0.1750, H - 0.03);
	m.skirt(a1, collar, C.steelDark);
	m.skirt(collar, shade, C.shell, C.shellLit);
	m.cap(shade, C.shellDark);
	m.box(0, 0.845, 0.1450, 0.0620, 0.0620, 0.0700, C.dark, C.darkLit);
	m.box(0, 0.845, 0.2050, 0.0330, 0.0330, 0.0300, C.ember, C.emberDim);
	return m;
}

for (const [name, build] of Object.entries({ tree, boulder, pedestal, synthoid, sentry, sentinel, meanie })) {
	emit(name, build());
}
